---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/base.yml
    - include: tasks/apps.yml tags=apps
    - include: tasks/user.yml tags=user
    - include: tasks/emacs-snapshot.yml tags=emacs
    - include: tasks/desktop.yml tags=desktop
    - include: tasks/vbox.yml tags=vbox

- hosts: localhost
  connection: local
  sudo: no

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/dotfiles.yml tags=dotfiles
