---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/base.yml
    - include: tasks/apps.yml
    - include: tasks/user.yml
    - include: tasks/emacs.yml

- hosts: localhost
  connection: local
  sudo: no

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/zsh.yml
    - include: tasks/emacs_config.yml
