# install virtualbox
#
#
# Copyright (C) 2013 Calogero Lo Leggio <kalos@nerdrug.org>
#
# This part of software is released under the terms of the GPLv3 license.
#
---
- name: install ruby utilities
  apt: pkg=$item state=installed
  with_items:
    - rbenv
    - ruby-build

# TODO
# install ruby-build plugin in home directory
