# Set zsh as default shell for $user and root
#
#
# Copyright (C) 2013 Calogero Lo Leggio <kalos@nerdrug.org>
#
# This part of software is released under the terms of the GPLv3 license.
#
---
- name: install zsh
  apt: pkg=zsh state=installed

- name: set zsh as default shell for $user and root
  user: shell=/bin/zsh name=$item
  with_items:
    - root
    - $user

- name: link ~/.oh-my-zsh for root
  file: src=$user_home/.oh-my-zsh
    dest=/root/.oh-my-zsh state=link

- name: link ~/.zshrc for root
  file: src=$user_home/.oh-my-zsh/custom/.zshrc
    dest=/root/.zshrc state=link
